#spring.application.name=service-order
#server.port=8000
#
## 配置nacos地址，将微服务注册到nacos上
#spring.cloud.nacos.server-addr=127.0.0.1:8848
## 导入Nacos的配置，service-order.properties是在Nacos上创建的配置名称，即Data ID
#spring.config.import=nacos:service-order.properties
## 如果引入了Nacos配置中心依赖，需要导入Nacos的配置，或禁用Nacos配置检查，否则服务启动失败
## spring.cloud.nacos.config.import-check.enabled=false