#spring.application.name=service-product
#server.port=9000
#
## 配置nacos地址，将微服务注册到nacos上
#spring.cloud.nacos.server-addr=127.0.0.1:8848
## 如果引入了Nacos配置中心依赖，需要导入Nacos的配置，或禁用Nacos配置检查，否则服务启动失败
#spring.cloud.nacos.config.import-check.enabled=false